import type { DataStatus } from "@/lib/types";
import { Badge } from "@/components/ui/feedback";

const CONFIG: Record<
  DataStatus,
  { label: string; tone: "neutral" | "primary" | "moderate" | "low" | "high" | "critical"; title: string }
> = {
  VERIFIED: {
    label: "Verified",
    tone: "low",
    title: "Verified observation from an authoritative source.",
  },
  DEMO: {
    label: "Demo data",
    tone: "primary",
    title: "Demonstration value generated by the prototype data layer — not a real observation.",
  },
  MODEL_PREDICTION: {
    label: "Model prediction",
    tone: "moderate",
    title: "Estimate produced by the prototype risk model — not a validated prediction.",
  },
  MODEL_FORECAST: {
    label: "Model forecast",
    tone: "moderate",
    title: "Extrapolation produced by the prototype model — uncertainty increases with horizon.",
  },
  SCENARIO: {
    label: "Scenario",
    tone: "high",
    title: "Scenario simulation output — a what-if estimate, not a forecast of real events.",
  },
};

export function DataStatusBadge({
  status,
  className,
}: {
  status: DataStatus;
  className?: string;
}) {
  const c = CONFIG[status];
  return (
    <abbr title={c.title} className="no-underline cursor-help">
      <Badge tone={c.tone} className={className}>
        [{c.label}]
      </Badge>
    </abbr>
  );
}
